name: DeployDev

on:
  push:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - uses: actions/setup-node@v1
        with:
          node-version: "18"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-frontend-access
          aws-region: ap-south-1

      - name: Build frontend and push on ECR
        run: |
          echo NEXT_PUBLIC_IFRAMELY_KEY=${{ secrets.NEXT_PUBLIC_IFRAMELY_KEY }} >> .env
          echo NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }} >> .env
          bash ./../deploy/deploy-ecr-image.sh dev-blogs ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/canopas-website-blogs

      - name: Deploy cloudformation stack
        id: canopas-website-dev-ECS-EC2-stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: canopas-website-dev-ECS-EC2-stack
          template: infrastructure/template.yml
          capabilities: CAPABILITY_IAM,CAPABILITY_NAMED_IAM
          timeout-in-minutes: "10"
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            EnvName=dev,
            Region=${{ secrets.AWS_REGION }},
            ClusterName=canopas-website-dev,
            ImageTag=${{ github.sha }}-${{ github.run_attempt }}-dev-blogs
